name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发，例如 v1.0.0
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # 根据需要调整Flutter版本
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Windows exe
        run: flutter build windows --release
        
      - name: Create Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/windows/x64/runner/Release/
          
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # 根据需要调整Flutter版本
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Android APK
        run: flutter build apk --release --split-per-abi
        
      - name: Create Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/*.apk
          
  release:
    needs: [build-windows, build-android]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # 只有在推送标签时才创建release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-exe
          path: ./windows-release/
          
      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-apks
          path: ./android-release/
          
      - name: Package Windows release
        run: |
          cd windows-release
          zip -r ../recipe-windows-${{ github.ref_name }}.zip .
          cd ..
          
      - name: Get release info
        id: release_info
        run: |
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "release_name=Recipe App ${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_info.outputs.tag_name }}
          release_name: ${{ steps.release_info.outputs.release_name }}
          body: |
            ## 新版本发布 ${{ steps.release_info.outputs.tag_name }}
            
            ### 下载说明：
            - **Windows**: 下载 `recipe-windows-*.zip` 文件，解压后运行 `recipe.exe`
            - **Android**: 
              - `app-arm64-v8a-release.apk` - 适用于现代64位Android设备（推荐）
              - `app-armeabi-v7a-release.apk` - 适用于32位ARM设备
              - `app-x86_64-release.apk` - 适用于x86_64架构设备
            
          draft: false
          prerelease: false
          
      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./recipe-windows-${{ steps.release_info.outputs.tag_name }}.zip
          asset_name: recipe-windows-${{ steps.release_info.outputs.tag_name }}.zip
          asset_content_type: application/zip
          
      - name: Upload Android ARM64 APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android-release/app-arm64-v8a-release.apk
          asset_name: recipe-android-arm64-${{ steps.release_info.outputs.tag_name }}.apk
          asset_content_type: application/vnd.android.package-archive
          
      - name: Upload Android ARMv7 APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android-release/app-armeabi-v7a-release.apk
          asset_name: recipe-android-armv7-${{ steps.release_info.outputs.tag_name }}.apk
          asset_content_type: application/vnd.android.package-archive
          
      - name: Upload Android x86_64 APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android-release/app-x86_64-release.apk
          asset_name: recipe-android-x86_64-${{ steps.release_info.outputs.tag_name }}.apk
          asset_content_type: application/vnd.android.package-archive
